### PR TITLE
Remove directory and payment limitation

### PR DESCRIPTION
**Pull request by felixhahnweilheim**
Please feel free to adjust the wording

### CODE REVIEW

**Comment by funkycram** [comment]
Thanks @felixhahnweilheim !
About the payment part you've removed, perhaps we could mention the https://marketplace.humhub.com/module/ecommerce module? 😉

**Comment by felixhahnweilheim** [comment]
Yes, I thought about it, but where? It is not a limitation...

Maybe an info box "Payment integration is now possible..."

**Comment by funkycram** [comment]
For "sub-spaces" limitation we have:
> Furthermore, the Professional Edition adds a space type feature for categorizing spaces, which allows one additional level of space classification.

Perhaps we could add something like that?

**Comment by felixhahnweilheim** [comment]
Can you suggest the whole paragraph? Then I can add it to the PR.
Or we wait for @luke- s opinion.

**Comment by funkycram** [comment]
Perhaps replace:
> There is currently no payment integration available. If you want to offer community services behind a payment wall,
you will have to implement a custom integration of your payment backend.

With:
> There is currently no payment integration available. If you want to offer community services behind a payment wall,
you will have to buy the [eCommerce module](https://marketplace.humhub.com/module/ecommerce) or implement a custom integration of your payment backend.

But yes, @luke- might have a better idea, as I'm the module creator, I don't feel like I belong to write this sentence...

**Comment by luke-** [comment]
I would be fine with both. Add an "eComerece" teaser here or remove this paragraph in the Limitations. 

@Semir1212 Can you please take a look into this?

**Comment by Semir1212** [comment]
Since we are currently working on our website and the related texts, I would suggest to put this issue on hold for the time being. @luke- 

Thank you for your contribution @felixhahnweilheim

**Review by luke- — APPROVED** [review]

**Pull request merged**
