### PR TITLE
Enh: Add translation command

### PR DESCRIPTION
**Pull request by ArchBlood**
See: https://community.humhub.com/s/general-discussion/?contentId=252587

### CODE REVIEW

**Comment by luke-** [comment]
@ArchBlood Thanks. Thanks, but these are really development Yii2 commands that shouldn't be needed in normal HumHub use.

Instead, could we provide a reference to the Yii2 documentation regarding the Yii2 commands?

**Comment by ArchBlood** [comment]
> @ArchBlood Thanks. Thanks, but these are really development Yii2 commands that shouldn't be needed in normal HumHub use.
> 
> Instead, could we provide a reference to the Yii2 documentation regarding the Yii2 commands?

Well that is rather hard for the common user when it comes to development of their own modules

As you'll see in [comment#41010](https://community.humhub.com/comment/perma?id=41010) that if reading the Yii2 Docs the use of `php yii message/extract module-id` is needed, but in HumHub this does not work whereas in [comment#41037](https://community.humhub.com/comment/perma?id=41037) `php yii message/extract-module` does, I've not found any correct documentation on the commands themselves other than telling the user to use the `help` command which is also pretty vague on how to exactly use commands. Other than adding them to the docs here, maybe within a wiki?

**Comment by luke-** [comment]
I found following documentation page: https://docs.humhub.org/docs/develop/modules-i18n/
Seems this page is not added in the navigation. 

What do you think if we add this page to the navigation? It seems to cover the topic.

**Comment by ArchBlood** [comment]
> I found following documentation page: https://docs.humhub.org/docs/develop/modules-i18n/
> Seems this page is not added in the navigation. 
> 
> What do you think if we add this page to the navigation? It seems to cover the topic.

Yes, that would help a lot of future developers when it comes to translations.

**Pull request closed without merging**
